service: application

custom:
  tags:
    stage: ${env:STAGE}

provider:
  name: aws
  tags: ${self:custom.tags}

  # unable to use preset runtime if you need to build nodejs packages with binary bindings
  runtime: nodejs12.x

  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  timeout: 180
  memorySize: 2048

# custom package artifact in zip format
package:
  artifact: ./artifact.zip

functions:
  healthcheck:
    handler: handler.healthcheck
    events:
      - http: GET /
    environment:
      STAGE: ${env:STAGE}
    reservedConcurrency: 4

